//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMAT
    {
        public int SNO { get; set; }
        public string MCAT { get; set; }
        public string MAT { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> OSMANABAD { get; set; }
        public Nullable<double> LATUR { get; set; }
        public Nullable<double> BEED { get; set; }
    }
}
