//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public Nullable<double> ANO { get; set; }
        public Nullable<double> SrNO { get; set; }
        public string Chap { get; set; }
        public string INO { get; set; }
        public string PgNo { get; set; }
        public string CAT { get; set; }
        public string Ref { get; set; }
        public string DESCRIP { get; set; }
        public string Spec { get; set; }
        public string UnitF { get; set; }
        public string UnitS { get; set; }
        public Nullable<double> CompRate { get; set; }
        public Nullable<double> LRate { get; set; }
        public string MAT1 { get; set; }
        public string MAT2 { get; set; }
        public string MAT3 { get; set; }
        public string MAT4 { get; set; }
        public string MAT5 { get; set; }
        public string MAT6 { get; set; }
        public string MAT7 { get; set; }
        public string MAT8 { get; set; }
        public Nullable<double> RATE1 { get; set; }
        public Nullable<double> RATE2 { get; set; }
        public Nullable<double> RATE3 { get; set; }
        public Nullable<double> RATE4 { get; set; }
        public Nullable<double> RATE5 { get; set; }
        public Nullable<double> RATE6 { get; set; }
        public Nullable<double> RATE7 { get; set; }
        public Nullable<double> RATE8 { get; set; }
        public Nullable<double> XCelX { get; set; }
        public Nullable<double> XcelY { get; set; }
        public string XLPath { get; set; }
        public string RATYPE { get; set; }
        public bool SCADA { get; set; }
        public Nullable<double> SCADAPer { get; set; }
        public string Plastic { get; set; }
    }
}
