//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetail
    {
        public int Id { get; set; }
        public int WorkDataID { get; set; }
        public string ItemNo { get; set; }
        public string Number { get; set; }
        public string Length { get; set; }
        public string BreadthWidth { get; set; }
        public string DepthHeight { get; set; }
        public string GeometricalFormulas { get; set; }
        public string Qty { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
