//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAD_CHART
    {
        public double SR_NO { get; set; }
        public Nullable<double> KM { get; set; }
        public Nullable<double> TCostMachine { get; set; }
        public Nullable<double> TCostManual { get; set; }
    }
}
