//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASUREMENT
    {
        public int Item_Id { get; set; }
        public string Item_Description { get; set; }
        public string Measurment_Description { get; set; }
        public string Numbers { get; set; }
        public string Lenght { get; set; }
        public string Breadth { get; set; }
        public string Depth { get; set; }
        public string Geometry { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total_Quantity { get; set; }
        public string Unit { get; set; }
        public string Remarks { get; set; }
        public string Lift { get; set; }
        public Nullable<int> Sub_Estimate { get; set; }
    }
}
