//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int ID { get; set; }
        public string SUB_DIVISION { get; set; }
        public string JE_SO_AE2 { get; set; }
        public string DE_SDE_AE1_AEE { get; set; }
        public string Division { get; set; }
        public string EE { get; set; }
        public string Circle { get; set; }
        public string SE { get; set; }
        public string Region { get; set; }
        public string CE { get; set; }
    }
}
