//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_Analysis
    {
        public int ID { get; set; }
        public string SSR { get; set; }
        public string Item_No { get; set; }
        public string Item_Description { get; set; }
        public Nullable<int> Basic_Rates { get; set; }
        public string Unit { get; set; }
        public string Area { get; set; }
        public Nullable<int> Area_Percentage { get; set; }
        public Nullable<int> Area_Charges { get; set; }
        public Nullable<int> Sub_Total { get; set; }
        public string Material1 { get; set; }
        public Nullable<int> Quantity1 { get; set; }
        public Nullable<int> Lead1 { get; set; }
        public Nullable<int> Lead_Charges1 { get; set; }
        public string Material2 { get; set; }
        public Nullable<int> Quantity2 { get; set; }
        public Nullable<int> Lead2 { get; set; }
        public Nullable<int> Lead_Charges2 { get; set; }
        public string Material3 { get; set; }
        public Nullable<int> Quantity3 { get; set; }
        public Nullable<int> Lead3 { get; set; }
        public Nullable<int> Lead_Charges3 { get; set; }
        public string Material4 { get; set; }
        public Nullable<int> Quantity4 { get; set; }
        public Nullable<int> Lead4 { get; set; }
        public Nullable<int> Lead_Charges4 { get; set; }
        public string Material5 { get; set; }
        public Nullable<int> Quantity5 { get; set; }
        public Nullable<int> Lead5 { get; set; }
        public Nullable<int> Lead_Charges5 { get; set; }
        public string Material6 { get; set; }
        public Nullable<int> Quantity6 { get; set; }
        public Nullable<int> Lead6 { get; set; }
        public Nullable<int> Lead_Charges6 { get; set; }
        public string Material7 { get; set; }
        public Nullable<int> Lead7 { get; set; }
        public Nullable<int> Lead_Charges7 { get; set; }
        public string Material8 { get; set; }
        public Nullable<int> Quantity8 { get; set; }
        public Nullable<int> Lead8 { get; set; }
        public Nullable<int> Lead_Charges8 { get; set; }
        public string Material9 { get; set; }
        public Nullable<int> Quantity9 { get; set; }
        public Nullable<int> Lead9 { get; set; }
        public Nullable<int> Lead_Charges9 { get; set; }
        public string Material10 { get; set; }
        public Nullable<int> Quantity10 { get; set; }
        public Nullable<int> Lead10 { get; set; }
        public Nullable<int> Lead_Charges10 { get; set; }
        public Nullable<int> Total_Lead_Charges { get; set; }
        public string Royalty { get; set; }
        public Nullable<int> Royalty_charges { get; set; }
        public string Other { get; set; }
        public Nullable<int> Other_Charges { get; set; }
        public string Other1 { get; set; }
        public Nullable<int> Other_Charges1 { get; set; }
        public Nullable<int> Completed_Rate { get; set; }
        public string Remarks { get; set; }
    }
}
