//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDCRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDataDetail
    {
        public int Id { get; set; }
        public string NameOfWork { get; set; }
        public string SSRRate { get; set; }
        public string Department { get; set; }
        public string HeadOfAccounts { get; set; }
        public string Area { get; set; }
        public string SubDivsion { get; set; }
        public string Divison { get; set; }
        public string Circle { get; set; }
        public string Region { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
